services:
  jupyter:
    image: jupyter/base-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - jupyter_data:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''  # disables auth
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - jupyter
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

volumes:
  jupyter_data:
